[project]
site_name = "AVPS OPT-NC"
site_description = "Avis de Vacances de Poste de l'Office des Postes et Télécommunications de Nouvelle-Calédonie"
site_author = "OPT-NC"
site_url = "https://opt-nc.github.io/avps/"
repo_url = "https://github.com/opt-nc/avps"
repo_name = "opt-nc/avps"

# Dossiers sources et destination
docs_dir = "data"
site_dir = "site"

# Métadonnées pour les réseaux sociaux (SEO & Social Preview)
[project.extra]
social_image = "assets/logo.png"
twitter_card = "summary_large_image"
twitter_site = "@OPT_NC"

# Inclure le flux RSS dans le build final
extra_files = ["feed.xml"]

copyright = """
Copyright &copy; 2026 OPT-NC<br>
<small>Dernière mise à jour : 29/04/2026 à 11:28 (Nouméa) | Commit : <a href="https://github.com/opt-nc/avps/commit/94602dd" target="_blank">94602dd</a></small><br>
<small>Propulsé par <a href="https://github.com/opt-nc/zensical" target="_blank">0.0.37</a></small>
"""

[project.theme]
name = "material"
language = "fr"
logo = "assets/logo.png"
favicon = "assets/logo.png"
custom_dir = "overrides"

# Icônes du site
icon.repo = "material/github"

# Options de navigation et recherche
features = [
    "navigation.top",          # Bouton "Retour en haut"
    "navigation.tracking",     # Mise à jour de l'URL au défilement
    "navigation.footer",       # Boutons Suivant/Précédent entre les avis
    "search.suggest",          # Suggestions de recherche
    "search.highlight"         # Surlignage des résultats de recherche
]

# Mode sombre / Mode clair
[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/brightness-4"
toggle.name = "Passer au mode clair"

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/brightness-7"
toggle.name = "Passer au mode sombre"

# Liens sociaux et institutionnels
[[project.extra.social]]
icon = "material/github"
link = "https://github.com/opt-nc/avps"
name = "Code source sur GitHub"

[[project.extra.social]]
icon = "material/rss"
link = "https://opt-nc.github.io/avps/feed.xml"
name = "Flux RSS des offres"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/opt-new-caledonia"
name = "LinkedIn OPT-NC"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/OPT_NC"
name = "X (Twitter) OPT-NC"

[[project.extra.social]]
icon = "material/earth"
link = "https://office.opt.nc/fr/emploi-et-carriere/postuler-lopt-nc/avp"
name = "Site Institutionnel OPT-NC"

# --- CUSTOM CSS POUR LES BADGES ---
extra_css = ["assets/custom.css"]


